import type { Knob, LinkDef, NodeDef, Scenario } from "./types";

const knob = (k: Knob) => k;

const client = (id: string, label: string, x: number, y: number): NodeDef => ({
  id,
  kind: "client",
  label,
  x,
  y,
  baseLatencyMs: 0,
  capacityRps: Infinity,
  queueLimit: Infinity,
});

const playground = (): Scenario => {
  const nodes: NodeDef[] = [
    client("users", "users", 80, 300),
    {
      id: "edge-cache",
      kind: "cache",
      label: "edge cache",
      x: 250,
      y: 300,
      baseLatencyMs: 4,
      capacityRps: 8000,
      queueLimit: 400,
      hitRatio: 0.65,
      ttlMs: 8000,
      refillMs: 2500,
    },
    {
      id: "ratelimit",
      kind: "ratelimiter",
      label: "rate limit",
      x: 425,
      y: 300,
      baseLatencyMs: 1,
      capacityRps: Infinity,
      queueLimit: 0,
      refillRps: 1200,
      bucketSize: 200,
    },
    {
      id: "lb",
      kind: "lb",
      label: "load balancer",
      x: 600,
      y: 300,
      baseLatencyMs: 2,
      capacityRps: Infinity,
      queueLimit: 500,
      targets: ["api-a", "api-b"],
    },
    {
      id: "api-a",
      kind: "service",
      label: "api-a",
      x: 790,
      y: 165,
      baseLatencyMs: 60,
      capacityRps: 700,
      queueLimit: 60,
    },
    {
      id: "api-b",
      kind: "service",
      label: "api-b",
      x: 790,
      y: 435,
      baseLatencyMs: 60,
      capacityRps: 700,
      queueLimit: 60,
    },
    {
      id: "db",
      kind: "db",
      label: "postgres",
      x: 985,
      y: 300,
      baseLatencyMs: 25,
      capacityRps: 2500,
      queueLimit: 300,
      replicaLagMs: 0,
      writeFraction: 0.3,
    },
  ];
  const links: LinkDef[] = [
    { id: "l1", from: "users", to: "edge-cache", latencyMs: 6 },
    { id: "l2", from: "edge-cache", to: "ratelimit", latencyMs: 3 },
    { id: "l3", from: "ratelimit", to: "lb", latencyMs: 3 },
    { id: "l4", from: "lb", to: "api-a", latencyMs: 12 },
    { id: "l5", from: "lb", to: "api-b", latencyMs: 16 },
    { id: "l6", from: "api-a", to: "db", latencyMs: 8 },
    { id: "l7", from: "api-b", to: "db", latencyMs: 8 },
  ];
  return {
    id: "playground",
    title: "Playground",
    blurb: "The whole stack: edge cache, rate limiter, two API instances and Postgres.",
    lesson:
      "A request crosses every layer; each layer can either absorb a burst, shed it early, or turn it into queueing delay.",
    tips: [
      "Push arrival rate past 1200 rps — the rate limiter starts shedding with 429s.",
      "Kill api-a in the inspector and watch round-robin keep sending it half the traffic.",
      "Turn on health checks, then least-inflight, and compare the error rate.",
      "Shrink the cache TTL to 1s and watch the hit ratio collapse.",
    ],
    start: "users",
    next: {
      users: ["edge-cache"],
      "edge-cache": ["ratelimit"],
      ratelimit: ["lb"],
      lb: [],
      "api-a": ["db"],
      "api-b": ["db"],
      db: [],
    },
    nodes,
    links,
    knobs: [
      knob({
        id: "arrival",
        label: "Arrival rate",
        type: "range",
        target: { scope: "global", field: "arrivalRps" },
        def: 600,
        min: 20,
        max: 4000,
        step: 20,
        unit: " rps",
      }),
      knob({
        id: "svc-cap",
        label: "API capacity",
        type: "range",
        target: { scope: "kind", kind: "service", field: "capacityRps" },
        def: 700,
        min: 50,
        max: 3000,
        step: 50,
        unit: " rps",
      }),
      knob({
        id: "svc-q",
        label: "API queue limit",
        type: "range",
        target: { scope: "kind", kind: "service", field: "queueLimit" },
        def: 60,
        min: 0,
        max: 400,
        step: 10,
      }),
      knob({
        id: "cache-ttl",
        label: "Cache TTL",
        type: "range",
        target: { scope: "node", id: "edge-cache", field: "ttlMs" },
        def: 8000,
        min: 500,
        max: 60000,
        step: 500,
        unit: " ms",
      }),
      knob({
        id: "cache-hit",
        label: "Cache hit ratio",
        type: "range",
        target: { scope: "node", id: "edge-cache", field: "hitRatio" },
        def: 0.65,
        min: 0,
        max: 1,
        step: 0.05,
      }),
      knob({
        id: "rl-rate",
        label: "Rate limit",
        type: "range",
        target: { scope: "node", id: "ratelimit", field: "refillRps" },
        def: 1200,
        min: 50,
        max: 5000,
        step: 50,
        unit: " rps",
      }),
      knob({
        id: "sf",
        label: "Single-flight (coalesce misses)",
        type: "toggle",
        target: { scope: "global", field: "singleFlight" },
        def: false,
      }),
      knob({
        id: "lb-strat",
        label: "LB strategy",
        type: "select",
        target: { scope: "global", field: "lbStrategy" },
        def: "round-robin",
        options: [
          { value: "round-robin", label: "round-robin" },
          { value: "random", label: "random" },
          { value: "least-inflight", label: "least-inflight" },
          { value: "least-latency", label: "least-latency" },
          { value: "p2c", label: "power of two choices" },
          { value: "sticky", label: "sticky sessions" },
        ],
      }),
      knob({
        id: "health",
        label: "Health checks",
        type: "toggle",
        target: { scope: "global", field: "healthChecks" },
        def: true,
      }),
      knob({
        id: "timeout",
        label: "Client timeout",
        type: "range",
        target: { scope: "global", field: "timeoutMs" },
        def: 4000,
        min: 500,
        max: 12000,
        step: 500,
        unit: " ms",
      }),
      knob({
        id: "db-lag",
        label: "Replica lag",
        type: "range",
        target: { scope: "node", id: "db", field: "replicaLagMs" },
        def: 0,
        min: 0,
        max: 8000,
        step: 100,
        unit: " ms",
      }),
    ],
  };
};

const stampede = (): Scenario => {
  const nodes: NodeDef[] = [
    client("users", "users", 110, 300),
    {
      id: "cache",
      kind: "cache",
      label: "product cache",
      x: 380,
      y: 300,
      baseLatencyMs: 5,
      capacityRps: 8000,
      queueLimit: 500,
      hitRatio: 0.9,
      ttlMs: 6000,
      refillMs: 4000,
    },
    {
      id: "catalog",
      kind: "service",
      label: "catalog service",
      x: 660,
      y: 300,
      baseLatencyMs: 900,
      capacityRps: 250,
      queueLimit: 80,
    },
    {
      id: "db",
      kind: "db",
      label: "postgres",
      x: 940,
      y: 300,
      baseLatencyMs: 40,
      capacityRps: 900,
      queueLimit: 120,
    },
  ];
  const links: LinkDef[] = [
    { id: "s1", from: "users", to: "cache", latencyMs: 6 },
    { id: "s2", from: "cache", to: "catalog", latencyMs: 8 },
    { id: "s3", from: "catalog", to: "db", latencyMs: 6 },
  ];
  return {
    id: "stampede",
    title: "Cache stampede",
    blurb: "A shared cache in front of one slow service. Every TTL expiry is a thundering herd.",
    lesson:
      "When the TTL lapses, every concurrent request misses at once and piles onto the service. Single-flight lets one request refill the cache while the rest wait — same work, a fraction of the load.",
    tips: [
      "Leave single-flight off and wait for an expiry: the service queue spikes and 503s appear.",
      "Turn single-flight on: identical expiry, flat service load.",
      "Shorten the TTL to 1s — expiries become constant with single-flight, brutal without.",
      "Raise the service latency to 2000 ms to make the herd window wider.",
    ],
    start: "users",
    next: {
      users: ["cache"],
      cache: ["catalog"],
      catalog: ["db"],
      db: [],
    },
    nodes,
    links,
    knobs: [
      knob({
        id: "arrival",
        label: "Arrival rate",
        type: "range",
        target: { scope: "global", field: "arrivalRps" },
        def: 400,
        min: 20,
        max: 3000,
        step: 20,
        unit: " rps",
      }),
      knob({
        id: "sf",
        label: "Single-flight (coalesce misses)",
        type: "toggle",
        target: { scope: "global", field: "singleFlight" },
        def: false,
      }),
      knob({
        id: "ttl",
        label: "Cache TTL",
        type: "range",
        target: { scope: "node", id: "cache", field: "ttlMs" },
        def: 6000,
        min: 1000,
        max: 60000,
        step: 500,
        unit: " ms",
      }),
      knob({
        id: "refill",
        label: "Refill (cold) window",
        type: "range",
        target: { scope: "node", id: "cache", field: "refillMs" },
        def: 4000,
        min: 500,
        max: 15000,
        step: 250,
        unit: " ms",
      }),
      knob({
        id: "svc-lat",
        label: "Service latency",
        type: "range",
        target: { scope: "node", id: "catalog", field: "baseLatencyMs" },
        def: 900,
        min: 50,
        max: 3000,
        step: 50,
        unit: " ms",
      }),
      knob({
        id: "svc-cap",
        label: "Service capacity",
        type: "range",
        target: { scope: "node", id: "catalog", field: "capacityRps" },
        def: 250,
        min: 20,
        max: 2000,
        step: 10,
        unit: " rps",
      }),
      knob({
        id: "timeout",
        label: "Client timeout",
        type: "range",
        target: { scope: "global", field: "timeoutMs" },
        def: 5000,
        min: 1000,
        max: 15000,
        step: 500,
        unit: " ms",
      }),
    ],
  };
};

const backpressure = (): Scenario => {
  const nodes: NodeDef[] = [
    client("users", "users", 100, 300),
    {
      id: "lb",
      kind: "lb",
      label: "load balancer",
      x: 340,
      y: 300,
      baseLatencyMs: 2,
      capacityRps: Infinity,
      queueLimit: 1000,
      targets: ["api-a", "api-b"],
    },
    {
      id: "api-a",
      kind: "service",
      label: "api-a",
      x: 620,
      y: 165,
      baseLatencyMs: 80,
      capacityRps: 400,
      queueLimit: 40,
    },
    {
      id: "api-b",
      kind: "service",
      label: "api-b",
      x: 620,
      y: 435,
      baseLatencyMs: 80,
      capacityRps: 400,
      queueLimit: 40,
    },
    {
      id: "db",
      kind: "db",
      label: "postgres",
      x: 900,
      y: 300,
      baseLatencyMs: 30,
      capacityRps: 2000,
      queueLimit: 500,
    },
  ];
  const links: LinkDef[] = [
    { id: "b1", from: "users", to: "lb", latencyMs: 6 },
    { id: "b2", from: "lb", to: "api-a", latencyMs: 10 },
    { id: "b3", from: "lb", to: "api-b", latencyMs: 10 },
    { id: "b4", from: "api-a", to: "db", latencyMs: 6 },
    { id: "b5", from: "api-b", to: "db", latencyMs: 6 },
  ];
  return {
    id: "backpressure",
    title: "Queue backpressure",
    blurb: "Two API instances with a shallow queue in front of a fast database.",
    lesson:
      "Once arrival rate exceeds capacity the queue can only do two things: grow (latency climbs linearly) or fill up (excess is rejected with 503). Shedding early keeps p95 honest; absorbing everything makes every request slow.",
    tips: [
      "Raise arrival rate to 1500 rps — 800 rps of capacity means the queue fills in a second.",
      "Set the queue limit to 0 and the service becomes a strict shedder: errors spike, p95 stays flat.",
      "Set the queue to 400 and errors vanish while p95 grows past the client timeout.",
      "Cut service latency to 10 ms and watch throughput rise to its capacity ceiling.",
    ],
    start: "users",
    next: {
      users: ["lb"],
      lb: [],
      "api-a": ["db"],
      "api-b": ["db"],
      db: [],
    },
    nodes,
    links,
    knobs: [
      knob({
        id: "arrival",
        label: "Arrival rate",
        type: "range",
        target: { scope: "global", field: "arrivalRps" },
        def: 700,
        min: 50,
        max: 6000,
        step: 50,
        unit: " rps",
      }),
      knob({
        id: "svc-cap",
        label: "API capacity (both)",
        type: "range",
        target: { scope: "kind", kind: "service", field: "capacityRps" },
        def: 400,
        min: 50,
        max: 3000,
        step: 25,
        unit: " rps",
      }),
      knob({
        id: "svc-q",
        label: "API queue limit",
        type: "range",
        target: { scope: "kind", kind: "service", field: "queueLimit" },
        def: 40,
        min: 0,
        max: 500,
        step: 10,
      }),
      knob({
        id: "svc-lat",
        label: "API latency",
        type: "range",
        target: { scope: "kind", kind: "service", field: "baseLatencyMs" },
        def: 80,
        min: 5,
        max: 1000,
        step: 5,
        unit: " ms",
      }),
      knob({
        id: "timeout",
        label: "Client timeout",
        type: "range",
        target: { scope: "global", field: "timeoutMs" },
        def: 4000,
        min: 500,
        max: 15000,
        step: 500,
        unit: " ms",
      }),
    ],
  };
};

const ratelimit = (): Scenario => {
  const nodes: NodeDef[] = [
    client("users", "users", 110, 300),
    {
      id: "gw",
      kind: "ratelimiter",
      label: "rate limiter",
      x: 380,
      y: 300,
      baseLatencyMs: 1,
      capacityRps: Infinity,
      queueLimit: 0,
      refillRps: 500,
      bucketSize: 50,
    },
    {
      id: "api",
      kind: "service",
      label: "api",
      x: 660,
      y: 300,
      baseLatencyMs: 120,
      capacityRps: 600,
      queueLimit: 120,
    },
    {
      id: "db",
      kind: "db",
      label: "postgres",
      x: 940,
      y: 300,
      baseLatencyMs: 30,
      capacityRps: 1500,
      queueLimit: 200,
    },
  ];
  const links: LinkDef[] = [
    { id: "r1", from: "users", to: "gw", latencyMs: 5 },
    { id: "r2", from: "gw", to: "api", latencyMs: 6 },
    { id: "r3", from: "api", to: "db", latencyMs: 6 },
  ];
  return {
    id: "ratelimit",
    title: "Rate limiting",
    blurb: "A token bucket in front of a service that cannot keep up.",
    lesson:
      "The limiter converts a slow, invisible failure into a fast, explicit one: 429s at the edge instead of multi-second queueing everywhere. The cost is that the shed traffic is yours — you traded latency for availability of the core service.",
    tips: [
      "Set arrival to 2000 rps with a 500 rps limit: 75% of traffic fails instantly, the API stays healthy.",
      "Set the limit to 2000 and watch the API queue absorb everything until p95 explodes.",
      "Bucket size controls burst tolerance: 10 lets a spike through, 500 makes it a leaky bucket.",
      "Compare error type: the limiter's 429s are cheap, timeouts are expensive.",
    ],
    start: "users",
    next: {
      users: ["gw"],
      gw: ["api"],
      api: ["db"],
      db: [],
    },
    nodes,
    links,
    knobs: [
      knob({
        id: "arrival",
        label: "Arrival rate",
        type: "range",
        target: { scope: "global", field: "arrivalRps" },
        def: 900,
        min: 50,
        max: 6000,
        step: 50,
        unit: " rps",
      }),
      knob({
        id: "limit",
        label: "Allowed rate",
        type: "range",
        target: { scope: "node", id: "gw", field: "refillRps" },
        def: 500,
        min: 50,
        max: 5000,
        step: 50,
        unit: " rps",
      }),
      knob({
        id: "bucket",
        label: "Bucket depth (burst)",
        type: "range",
        target: { scope: "node", id: "gw", field: "bucketSize" },
        def: 50,
        min: 1,
        max: 800,
        step: 1,
      }),
      knob({
        id: "svc-cap",
        label: "API capacity",
        type: "range",
        target: { scope: "node", id: "api", field: "capacityRps" },
        def: 600,
        min: 50,
        max: 3000,
        step: 25,
        unit: " rps",
      }),
      knob({
        id: "svc-q",
        label: "API queue limit",
        type: "range",
        target: { scope: "node", id: "api", field: "queueLimit" },
        def: 120,
        min: 0,
        max: 500,
        step: 10,
      }),
    ],
  };
};

const lbScenario = (): Scenario => {
  const nodes: NodeDef[] = [
    client("users", "users", 100, 300),
    {
      id: "lb",
      kind: "lb",
      label: "load balancer",
      x: 350,
      y: 300,
      baseLatencyMs: 2,
      capacityRps: Infinity,
      queueLimit: 1000,
      targets: ["strong", "weak"],
    },
    {
      id: "strong",
      kind: "service",
      label: "api-a (800 rps)",
      x: 640,
      y: 165,
      baseLatencyMs: 50,
      capacityRps: 800,
      queueLimit: 50,
    },
    {
      id: "weak",
      kind: "service",
      label: "api-b (150 rps)",
      x: 640,
      y: 435,
      baseLatencyMs: 50,
      capacityRps: 150,
      queueLimit: 50,
    },
    {
      id: "db",
      kind: "db",
      label: "postgres",
      x: 920,
      y: 300,
      baseLatencyMs: 25,
      capacityRps: 2500,
      queueLimit: 400,
    },
  ];
  const links: LinkDef[] = [
    { id: "q1", from: "users", to: "lb", latencyMs: 6 },
    { id: "q2", from: "lb", to: "strong", latencyMs: 10 },
    { id: "q3", from: "lb", to: "weak", latencyMs: 10 },
    { id: "q4", from: "strong", to: "db", latencyMs: 6 },
    { id: "q5", from: "weak", to: "db", latencyMs: 6 },
  ];
  return {
    id: "lb",
    title: "Load balancer strategies",
    blurb: "One fast instance and one slow one behind the same balancer.",
    lesson:
      "Round-robin and random assume the pool is homogeneous. Least-inflight uses real-time feedback, so the weak instance only ever holds what it can serve — the balancer load-balances instead of traffic-splitting.",
    tips: [
      "Set arrival to 900 rps: round-robin overloads api-b while api-a idles.",
      "Switch to least-inflight at the same arrival rate — errors drop, p95 falls.",
      "Make both capacities equal and all strategies converge.",
      "Sticky sessions with two unequal instances is the worst of both worlds.",
    ],
    start: "users",
    next: {
      users: ["lb"],
      lb: [],
      strong: ["db"],
      weak: ["db"],
      db: [],
    },
    nodes,
    links,
    knobs: [
      knob({
        id: "arrival",
        label: "Arrival rate",
        type: "range",
        target: { scope: "global", field: "arrivalRps" },
        def: 900,
        min: 50,
        max: 4000,
        step: 25,
        unit: " rps",
      }),
      knob({
        id: "strat",
        label: "LB strategy",
        type: "select",
        target: { scope: "global", field: "lbStrategy" },
        def: "round-robin",
        options: [
          { value: "round-robin", label: "round-robin" },
          { value: "random", label: "random" },
          { value: "least-inflight", label: "least-inflight" },
          { value: "least-latency", label: "least-latency" },
          { value: "p2c", label: "power of two choices" },
          { value: "sticky", label: "sticky sessions" },
        ],
      }),
      knob({
        id: "cap-a",
        label: "api-a capacity",
        type: "range",
        target: { scope: "node", id: "strong", field: "capacityRps" },
        def: 800,
        min: 50,
        max: 3000,
        step: 25,
        unit: " rps",
      }),
      knob({
        id: "cap-b",
        label: "api-b capacity",
        type: "range",
        target: { scope: "node", id: "weak", field: "capacityRps" },
        def: 150,
        min: 25,
        max: 3000,
        step: 25,
        unit: " rps",
      }),
      knob({
        id: "q",
        label: "Instance queue limit",
        type: "range",
        target: { scope: "kind", kind: "service", field: "queueLimit" },
        def: 50,
        min: 0,
        max: 400,
        step: 10,
      }),
    ],
  };
};

const partition = (): Scenario => {
  const nodes: NodeDef[] = [
    client("users", "users", 100, 300),
    {
      id: "lb",
      kind: "lb",
      label: "load balancer",
      x: 350,
      y: 300,
      baseLatencyMs: 2,
      capacityRps: Infinity,
      queueLimit: 1000,
      targets: ["api-a", "api-b"],
    },
    {
      id: "api-a",
      kind: "service",
      label: "api-a",
      x: 640,
      y: 165,
      baseLatencyMs: 70,
      capacityRps: 700,
      queueLimit: 60,
    },
    {
      id: "api-b",
      kind: "service",
      label: "api-b",
      x: 640,
      y: 435,
      baseLatencyMs: 70,
      capacityRps: 700,
      queueLimit: 60,
    },
    {
      id: "db",
      kind: "db",
      label: "postgres",
      x: 920,
      y: 300,
      baseLatencyMs: 25,
      capacityRps: 2500,
      queueLimit: 400,
    },
  ];
  const links: LinkDef[] = [
    { id: "p1", from: "users", to: "lb", latencyMs: 6 },
    { id: "p2", from: "lb", to: "api-a", latencyMs: 10 },
    { id: "p3", from: "lb", to: "api-b", latencyMs: 10, partitioned: true },
    { id: "p4", from: "api-a", to: "db", latencyMs: 6 },
    { id: "p5", from: "api-b", to: "db", latencyMs: 6 },
  ];
  return {
    id: "partition",
    title: "Network partition",
    blurb: "Half the pool is unreachable — requests vanish into a black hole.",
    lesson:
      "A partitioned link does not refuse connections, it swallows them: every affected request waits for the full client timeout. Health checks recover it in one probe interval; least-inflight recovers for free, because stuck requests stay inflight.",
    tips: [
      "Watch p95: stuck requests dominate it long before the error rate looks bad.",
      "Turn health checks on — api-b is skipped within a second and errors collapse.",
      "Switch to least-inflight with checks off: inflight counts alone route around the hole.",
      "Repair the link from the inspector and watch traffic flow back.",
    ],
    start: "users",
    next: {
      users: ["lb"],
      lb: [],
      "api-a": ["db"],
      "api-b": ["db"],
      db: [],
    },
    nodes,
    links,
    knobs: [
      knob({
        id: "arrival",
        label: "Arrival rate",
        type: "range",
        target: { scope: "global", field: "arrivalRps" },
        def: 700,
        min: 50,
        max: 4000,
        step: 25,
        unit: " rps",
      }),
      knob({
        id: "cut",
        label: "Partition LB → api-b",
        type: "toggle",
        target: { scope: "link", id: "p3", field: "partitioned" },
        def: true,
      }),
      knob({
        id: "strat",
        label: "LB strategy",
        type: "select",
        target: { scope: "global", field: "lbStrategy" },
        def: "round-robin",
        options: [
          { value: "round-robin", label: "round-robin" },
          { value: "random", label: "random" },
          { value: "least-inflight", label: "least-inflight" },
          { value: "least-latency", label: "least-latency" },
          { value: "p2c", label: "power of two choices" },
          { value: "sticky", label: "sticky sessions" },
        ],
      }),
      knob({
        id: "health",
        label: "Health checks",
        type: "toggle",
        target: { scope: "global", field: "healthChecks" },
        def: false,
      }),
      knob({
        id: "timeout",
        label: "Client timeout",
        type: "range",
        target: { scope: "global", field: "timeoutMs" },
        def: 4000,
        min: 500,
        max: 15000,
        step: 500,
        unit: " ms",
      }),
    ],
  };
};

const staleness = (): Scenario => {
  const nodes: NodeDef[] = [
    client("users", "users", 130, 300),
    {
      id: "api",
      kind: "service",
      label: "api",
      x: 460,
      y: 300,
      baseLatencyMs: 60,
      capacityRps: 800,
      queueLimit: 80,
    },
    {
      id: "db",
      kind: "db",
      label: "postgres (async replica)",
      x: 810,
      y: 300,
      baseLatencyMs: 20,
      capacityRps: 2000,
      queueLimit: 300,
      replicaLagMs: 2500,
      writeFraction: 0.3,
    },
  ];
  const links: LinkDef[] = [
    { id: "t1", from: "users", to: "api", latencyMs: 6 },
    { id: "t2", from: "api", to: "db", latencyMs: 5 },
  ];
  return {
    id: "staleness",
    title: "Replication lag",
    blurb: "Reads go to an async replica. Nothing fails — the answers are just old.",
    lesson:
      "Staleness is the error nobody's monitoring: 100% of requests return 200 while a share of reads serve data that is replicaLagMs out of date. Read-your-writes needs routing, not retries.",
    tips: [
      "Push lag to 5000 ms — stale share tracks the read fraction exactly.",
      "Set the write fraction to 0: every read is stale, nothing is ever wrong status-wise.",
      "Raising capacity does nothing here — the problem is consistency, not throughput.",
      "Compare with the partition scenario: loud failures beat silent ones.",
    ],
    start: "users",
    next: {
      users: ["api"],
      api: ["db"],
      db: [],
    },
    nodes,
    links,
    knobs: [
      knob({
        id: "arrival",
        label: "Arrival rate",
        type: "range",
        target: { scope: "global", field: "arrivalRps" },
        def: 500,
        min: 20,
        max: 4000,
        step: 20,
        unit: " rps",
      }),
      knob({
        id: "lag",
        label: "Replica lag",
        type: "range",
        target: { scope: "node", id: "db", field: "replicaLagMs" },
        def: 2500,
        min: 0,
        max: 15000,
        step: 100,
        unit: " ms",
      }),
      knob({
        id: "writes",
        label: "Write share",
        type: "range",
        target: { scope: "node", id: "db", field: "writeFraction" },
        def: 0.3,
        min: 0,
        max: 1,
        step: 0.05,
      }),
      knob({
        id: "db-lat",
        label: "DB latency",
        type: "range",
        target: { scope: "node", id: "db", field: "baseLatencyMs" },
        def: 20,
        min: 5,
        max: 300,
        step: 5,
        unit: " ms",
      }),
      knob({
        id: "svc-cap",
        label: "API capacity",
        type: "range",
        target: { scope: "node", id: "api", field: "capacityRps" },
        def: 800,
        min: 50,
        max: 3000,
        step: 25,
        unit: " rps",
      }),
    ],
  };
};

const circuit = (): Scenario => {
  const nodes: NodeDef[] = [
    client("users", "users", 100, 300),
    {
      id: "breaker",
      kind: "breaker",
      label: "circuit breaker",
      x: 360,
      y: 300,
      baseLatencyMs: 2,
      capacityRps: Infinity,
      queueLimit: 0,
      enabled: true,
      tripsAt: 0.4,
      cooldownMs: 4000,
      probeLimit: 2,
      cbWindow: 100,
    },
    {
      id: "catalog",
      kind: "service",
      label: "flaky catalog",
      x: 640,
      y: 300,
      baseLatencyMs: 180,
      capacityRps: 450,
      queueLimit: 80,
    },
    {
      id: "db",
      kind: "db",
      label: "postgres",
      x: 920,
      y: 300,
      baseLatencyMs: 25,
      capacityRps: 2000,
      queueLimit: 300,
    },
  ];
  const links: LinkDef[] = [
    { id: "cb1", from: "users", to: "breaker", latencyMs: 6 },
    { id: "cb2", from: "breaker", to: "catalog", latencyMs: 8, errorProb: 0.0 },
    { id: "cb3", from: "catalog", to: "db", latencyMs: 6 },
  ];
  return {
    id: "circuit",
    title: "Circuit breaker",
    blurb: "A breaker in front of a dependency that goes down or turns flaky.",
    lesson:
      "A down dependency doesn't refuse quickly — every request sits there until the client gives up. That is the slow failure circuit breakers exist to contain: watch the recent error rate, and past a threshold fail fast with 503, then probe to recover.",
    tips: [
      "Flip Link down with the breaker off: every request waits the full timeout, p95 pins at ~4000 ms and inflight piles up.",
      "Turn the breaker on: within a second it trips OPEN, requests fail in ms, and p95 collapses — yet the error count is the same, it just arrives fast.",
      "Lower trips-at to 0.2 to cut in sooner; raise cooldown so an unhealthy dependency can't flap it open and closed.",
      "Repair the link: half-open probes succeed, the circuit closes, and traffic flows again by itself.",
    ],
    start: "users",
    next: {
      users: ["breaker"],
      breaker: ["catalog"],
      catalog: ["db"],
      db: [],
    },
    nodes,
    links,
    knobs: [
      knob({
        id: "arrival",
        label: "Arrival rate",
        type: "range",
        target: { scope: "global", field: "arrivalRps" },
        def: 400,
        min: 20,
        max: 3000,
        step: 20,
        unit: " rps",
      }),
      knob({
        id: "breaker",
        label: "Circuit breaker enabled",
        type: "toggle",
        target: { scope: "node", id: "breaker", field: "enabled" },
        def: true,
      }),
      knob({
        id: "link-down",
        label: "Dependency link down",
        type: "toggle",
        target: { scope: "link", id: "cb2", field: "partitioned" },
        def: false,
      }),
      knob({
        id: "flaky",
        label: "Dependency flakiness",
        type: "range",
        target: { scope: "link", id: "cb2", field: "errorProb" },
        def: 0,
        min: 0,
        max: 0.8,
        step: 0.05,
      }),
      knob({
        id: "trips-at",
        label: "Trips at (error rate)",
        type: "range",
        target: { scope: "node", id: "breaker", field: "tripsAt" },
        def: 0.4,
        min: 0.05,
        max: 0.9,
        step: 0.05,
      }),
      knob({
        id: "cooldown",
        label: "Cooldown before probing",
        type: "range",
        target: { scope: "node", id: "breaker", field: "cooldownMs" },
        def: 4000,
        min: 500,
        max: 20000,
        step: 500,
        unit: " ms",
      }),
      knob({
        id: "probe-limit",
        label: "Half-open probe limit",
        type: "range",
        target: { scope: "node", id: "breaker", field: "probeLimit" },
        def: 2,
        min: 1,
        max: 10,
        step: 1,
      }),
      knob({
        id: "timeout",
        label: "Client timeout",
        type: "range",
        target: { scope: "global", field: "timeoutMs" },
        def: 4000,
        min: 500,
        max: 15000,
        step: 500,
        unit: " ms",
      }),
    ],
  };
};

export const SCENARIOS: Scenario[] = [
  playground(),
  stampede(),
  backpressure(),
  ratelimit(),
  lbScenario(),
  partition(),
  staleness(),
  circuit(),
];

export const scenarioById = (id: string): Scenario =>
  SCENARIOS.find((s) => s.id === id) ?? SCENARIOS[0];
